name: Build
on: [push, pull_request]
env:
  CI: true

jobs:
  run:
    name: Node ${{ matrix.node }}
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        node: [10.19, 12, 14, 15]

    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Validate composer.json and composer.lock
        run: composer validate

      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v2
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-

      - name: Set Node.js version
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

      - name: Composer
        if: steps.composer-cache.outputs.cache-hit != 'true'
        run: composer install
 
      - run: node --version
      - run: npm --version

      - name: Build
        run: npm i
